version: "3.7"

services:
  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:latest
    build:
      context: .
    volumes:
      - akaunting-data:/var/www/html
    restart: unless-stopped
    env_file:
      - env/run.env
    environment:
      - AKAUNTING_SETUP
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.service=${TRAEFIK_SERVICE}"
      - "traefik.http.services.${TRAEFIK_SERVICE}.loadbalancer.server.port=80"
    networks:
      - database
      - traefik

volumes:
  akaunting-data:

networks:
  database:
    external: true
  traefik:
    external: true
